### ISSUE TITLE
Excelente trabajo

### ISSUE THREAD

**Issue by danmt** [GabJaJ/Solana-HDB#1]
Que bien que tengas capturas y todo de las clases! Estas aprobado!

**Comment by GabJaJ** [comment]
Muchas gracias Daniel!! Si! Quiero dejar una documentación en capturas y tener ese registro a mano. A darle átomos!!Un abrazo grande!El 8 feb 2024, a la(s) 18:23, Daniel Marin ***@***.***> escribió:﻿
Que bien que tengas capturas y todo de las clases! Estas aprobado!
